# TensorFlow basics:

In [ ]:
#Steps to reproduce:

#Installation:

#pip install --upgrade pip
#!pip install tensorflow==2.0.0-alpha0
#or
# !pip install tensorflow
# OR
# !pip install --user tensorflow-gpu

In [2]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
import numpy as np

## Hello World!

In [3]:
hello = tf.constant("Hello World!")
with tf.Session() as sess:
    print(sess.run(hello))

b'Hello World!'


## Creating tensors:

In [4]:
hello = tf.constant("Hello World!")                         # String.
const_scalar = tf.constant(7)                               # A scalar tensor.
const_matrix = tf.constant([[1,2], [3,4]])                  # A matrix tensor.
mat_fill = tf.fill((4,4),9)                                 # A 4x4 tensor filled with 9s.
mat_zeros = tf.zeros((3,3))                                 # A 3x3 tensor filled with 0s.
mat_ones = tf.ones((5,5))                                   # A 5x5 tensor filled with 1s.
mat_randn = tf.random_normal((3,3), mean=0, stddev=1.0)     # 3x3 random normal tensor.
mat_randu = tf.random_uniform((4,4), minval=0, maxval=1.0)  # 4x4 random uniform tensor.

In [5]:
my_ops=[hello, const_scalar, const_matrix, mat_fill, mat_zeros, mat_ones, mat_randn, mat_randu]
with tf.Session() as sess:
    for op in my_ops:
        res = sess.run(op)
        print(type(res))
        print('\n')
        print(res)
        print('\n')

<class 'bytes'>


b'Hello World!'


<class 'numpy.int32'>


7


<class 'numpy.ndarray'>


[[1 2]
 [3 4]]


<class 'numpy.ndarray'>


[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


<class 'numpy.ndarray'>


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<class 'numpy.ndarray'>


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


<class 'numpy.ndarray'>


[[-2.66253    -0.49062663 -0.7210616 ]
 [ 1.9958326  -0.32988474  0.8111852 ]
 [ 0.06666844  0.9022085   0.23498912]]


<class 'numpy.ndarray'>


[[0.25093925 0.70829976 0.86149156 0.40779722]
 [0.2938372  0.09105074 0.8902552  0.43755865]
 [0.82638705 0.87730527 0.99109685 0.12194335]
 [0.3866434  0.8824408  0.5578474  0.88460743]]




## Math operations:

create two scalars ``n1`` and ``n2``  using ``tf.constant`` with any value of your choice and do the following operations: 
- **multplication** using ``tf.multiply`` and ``*``
- **addition** using ``tf.add`` and ``+``
- **pow** using ``tf.pow``

save each operation in a variable and run them using :

``
with tf.Session() as sess:
    sess.run(...)
    ...
``    

In [6]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1* n2
with tf.Session() as sess:
    print(sess.run(n3))

2


In [7]:
n1 = tf.constant(4)
n2 = tf.constant(5)
n3 = tf.add(n1,n2)
with tf.Session() as sess:
    print(sess.run(n3))

9


In [8]:
n1 = tf.constant(2)
n2 = tf.constant(3)
n3 = tf.multiply(n1,n2)
with tf.Session() as sess:
    print(sess.run(n3))

6


In [9]:
n1 = tf.constant(2)
n2 = tf.constant(3)
n3 = tf.pow(n1,n2)
with tf.Session() as sess:
    print(sess.run(n3))

8


## Matrix functions and operations:

create two variables ``tf.constant([[1,2], [3,4]])`` and ``tf.constant([[5, 6], [7, 8]])``
then perfom ``tf.matmul`` and ``tf.multiply``.
- run them using session.run() (just like the previous example)
- conclude the difference between the two operations

In [10]:
m1 = tf.constant([[1,2], [3,4]])
m2 = tf.constant([[1], [2]])
m3 = tf.matmul(m1, m2)                            # Matrix multiplication. Different from the element-wise multiplication with multiply().
with tf.Session() as sess:
    print(sess.run(m3))

[[ 5]
 [11]]


In [11]:
m1 = tf.constant([[1,2], [3,4]])
m2 = tf.constant([[5, 6], [7, 8]])
print(m1.shape)
print(m1)
print(m2)
m3 = tf.matmul(m1, m2) # rows×columns
with tf.Session() as sess:
    print(sess.run(m1))
    print(sess.run(m2))
    print(sess.run(m3))

(2, 2)
Tensor("Const_14:0", shape=(2, 2), dtype=int32)
Tensor("Const_15:0", shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [12]:
m3 = tf.multiply(m1, m2)
with tf.Session() as sess:
    print(sess.run(m3))

[[ 5 12]
 [21 32]]


In [13]:
m3 = m1*m2
with tf.Session() as sess:
    print(sess.run(m3))

[[ 5 12]
 [21 32]]


perform also ``+`` , ``-`` , ``/`` , use round with the last operation with 3 decimal places after comma.

In [14]:
m3 = m1 + m2
with tf.Session() as sess:
    print(sess.run(m3))

[[ 6  8]
 [10 12]]


In [15]:
m3 = m1-m2
with tf.Session() as sess:
    print(sess.run(m3))

[[-4 -4]
 [-4 -4]]


In [16]:
m3 = m1 / m2
with tf.Session() as sess:
    print(np.round(sess.run(m3),3))

[[0.2   0.333]
 [0.429 0.5  ]]


here are some other operations you can do using constant variables

In [17]:
# Matrix functions.
m = tf.constant([[1.0,2.0],[3.0,4.0]])
m_diagonal = tf.matrix_diag([1,2,3])
m_transpose = tf.matrix_transpose(m)
m_inverse = tf.matrix_inverse(m)
m_multiplied = tf.matmul(m, m_inverse)
m_determinant = tf.matrix_determinant(m)
my_matrices = [m, m_diagonal, m_transpose, m_inverse, m_multiplied, m_determinant]
with tf.Session() as sess:
    for mat in my_matrices:
        res = sess.run(mat)
        print(np.round(res,3))
        print('\n')

[[1. 2.]
 [3. 4.]]


[[1 0 0]
 [0 2 0]
 [0 0 3]]


[[1. 3.]
 [2. 4.]]


[[-2.   1. ]
 [ 1.5 -0.5]]


[[ 1.  0.]
 [-0.  1.]]


-2.0




## TensorFlow Variable:

there are threee way to initialize your variables

In [18]:
# Initializing Variables #1
x = tf.Variable(initial_value=5, name='x')       # Define.
y = tf.Variable(initial_value=6, name='y')       # Define.
f = (x - y)*y + 3                                # Define.
sess = tf.Session()
sess.run(x.initializer)                          # Initialize.
sess.run(y.initializer)                          # Initialize. 
res = sess.run(f)  
print(res)
sess.close()

-3


In [19]:
# Initializing Variables #2
x = tf.Variable(initial_value=3, name='x')       # Define.
y = tf.Variable(initial_value=2, name='y')       # Define.
f = x*y + y + 3                                  # Define.
with tf.Session() as sess:
    x.initializer.run()                          # Initialize. The same as "sess.run(x.initializer)".
    y.initializer.run()                          # Initialize. The same as "sess.run(y.initializer)".
    res = f.eval()                               # The same as "res = sess.run(f)".
print(res)

11


the following initialization method is the widely used 

In [20]:
# Initializing Variables #3
x = tf.Variable(initial_value=7, name='x')       # Define.
y = tf.Variable(initial_value=3, name='y')       # Define.
f = x*y*y - y - 1                                # Define.
init = tf.global_variables_initializer()         # will go through all variables and initialize them 
with tf.Session() as sess:
    sess.run(init)                               # Initialize wil happen after running sess.run(init).
    res = f.eval()                               # The same as "res = sess.run(f)".
print(res)

59


- create ``my_tensor`` using tf.random_uniform of shape ``(4,4)`` of zero mean and 1 std
- create ``my_var`` using ``tf.Variable`` with an initial value ``my_tensor``
- run a global initializer using ``tf.global_variables_initializer`` and store it in ``init``
- start a session as usual and run ``init`` to initialize your variables 

In [21]:
my_tensor = tf.random_uniform((4,4),0,1)
my_var = tf.Variable(initial_value = my_tensor)                  # Initial value from a tensor.
#my_matrix = np.random.uniform(0,1,(4,4))
#my_var = tf.Variable(initial_value = my_matrix)                  # Initial value from a Numpy array.
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)                                               
    print(sess.run(my_var))

[[0.29045868 0.01169014 0.44028783 0.4711765 ]
 [0.8589295  0.18977165 0.5858879  0.3032074 ]
 [0.840227   0.83634317 0.5731003  0.01872683]
 [0.34343147 0.4539262  0.6559149  0.25526953]]


## TensorFlow Placeholder

placeholders are different , they got initialized through run function using the ``feed_dict``.

**usage :** imagine a placeholder as booking a table at a restaurant ,in our case the guests are the input , you guessed it right **placeholders are used for input data** one cool property of placeholders is that you don't need to set number of observations
<br>

here's an example :

In [22]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
y = tf.multiply(a, b)
with tf.Session() as sess:
    res = sess.run(y, feed_dict={a:2, b:3})           # Feed the actual valules.
    print(res)

6.0


In [23]:
# Simulated data as NumPy array.
np.random.seed(123)
X1 = np.random.uniform(0.0, 1.0, (3,3))
X2 = np.random.normal(0.0, 1.0, (10,3))
b0 = np.array([1,2,3]).reshape((-1,1))
#
# The data may be a DataFrame.
# X1 = pd.DataFrame(X1)
# X2 = pd.DataFrame(X2)
#
X = tf.placeholder(tf.float32, shape=(None,3))       # "None" means that the number of rows is still undefined. 
b = tf.placeholder(tf.float32, shape=(3,1))
y = tf.matmul(X, b)
with tf.Session() as sess:
    print(sess.run(y, feed_dict={X:X1, b:b0}))       # Feed in the data.
    print("\n")
    print(sess.run(y, feed_dict={X:X2, b:b0}))       # Feed in the data.

[[1.9493022]
 [3.259572 ]
 [3.7932193]]


[[-5.1895514 ]
 [-0.47591597]
 [ 0.76363635]
 [ 4.6815934 ]
 [ 6.4029546 ]
 [-5.6862936 ]
 [-4.963093  ]
 [-8.809272  ]
 [-5.3064833 ]
 [ 3.0540478 ]]
